<a href="https://colab.research.google.com/github/EduMontiel19/PROBLEMARIO.-Operaciones-matriciales-y-vectoriales/blob/main/PROBLEMARIO_Operaciones_matriciales_y_vectoriales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROBLEMARIO. Operaciones matriciales y vectoriales**
##Elaborado por: Eduardo Montiel Salazar

##Ejercicio 1: Suma de matrices
Se realizó la suma de dos matrices del mismo tamaño, combinando cada elemento con su correspondiente. Con esta operación se obtuvo una nueva matriz que conserva la forma de las originales, pero con valores actualizados. Este procedimiento es básico en álgebra lineal para trabajar con datos representados matricialmente.

In [1]:
import numpy as np
A=np.array([[2,4,6], [1,3,5], [7,9,11]])
B=np.array([[12,10,8], [6,4,2], [0,-2,-4]])

C= A+B
print("Resultado de la suma de matrices: ")
print(C)

Resultado de la suma de matrices: 
[[14 14 14]
 [ 7  7  7]
 [ 7  7  7]]


##Ejercicio 2: Multiplicacion de matrices
Se efectuó la multiplicación de matrices siguiendo la regla de combinar filas con columnas. El resultado fue una nueva matriz que representa la composición de transformaciones lineales. Esta operación es esencial en muchos cálculos matemáticos y aplicaciones computacionales.

In [2]:
A=np.array([[2,1], [3,4], [5,6]])
B=np.array([[7,8], [9,10]])

C=A@B
print("Resultado de la multiplicación de matrices: ")
print(C)

Resultado de la multiplicación de matrices: 
[[ 23  26]
 [ 57  64]
 [ 89 100]]


##Ejercicio 3: Inversión de matriz
Se calcula la matriz inversa, la cual, multiplicada por la original, produce la identidad. La inversa solo existe si la matriz es no singular (determinante distinto de cero) y se usa para despejar incógnitas o revertir transformaciones lineales.

In [3]:
from sympy import Matrix
A= Matrix([[4,7,2], [2,6,8], [3,1,9]])
A_inv= A.inv()
print("Resultado de la inversa de la matriz: ")
print(A_inv)

Resultado de la inversa de la matriz: 
Matrix([[23/97, -61/194, 22/97], [3/97, 15/97, -14/97], [-8/97, 17/194, 5/97]])


##Ejercicio 4: Resolucion de sistemas de ecuaciones
Se plantean ecuaciones lineales y se encuentra el conjunto de valores que satisfacen todas a la vez. Dependiendo de la matriz de coeficientes, el sistema puede tener solución única, infinitas soluciones o no tener solución.

In [4]:
from sympy import symbols, Eq, solve
x, y, z = symbols('x y z')
#Definición de las ecuaciones
eq1=Eq(2*x + y + z, 8)
eq2=Eq(3*x + 5*y + 2*z, 21)
eq3=Eq(x + 2*y + 4*z, 11)
sol=solve((eq1, eq2, eq3), (x, y, z))
print("Solución del sistema de ecuaciones: ")
print(sol)

Solución del sistema de ecuaciones: 
{x: 53/23, y: 56/23, z: 22/23}


##Ejercicio 5: Determinante
Se calcula el determinante, un número que resume propiedades de la matriz: indica si es invertible, afecta el cambio de volumen que realiza la transformación y aparece en criterios de solución de sistemas y cambios de variable.

In [5]:
A= Matrix([[3,-2,1], [0,5,4], [2,1,7]])
det= A.det()
print("Determinante de la matriz: ")
print(det)

Determinante de la matriz: 
67


##Ejercicio 6: Producto cruz
Se calcula el producto cruz de dos vectores en el espacio tridimensional. El resultado fue un vector perpendicular a ambos cuya magnitud representa el área del paralelogramo que forman. Este cálculo se utiliza en geometría, física y gráficos computacionales

In [6]:
A=np.array([2,3,-1])
B=np.array([1,-2,4])
C=np.cross(A,B)
print("Resultado del producto cruz: ")
print(C)

Resultado del producto cruz: 
[10 -9 -7]


##Ejercicio 7: Proyeccion ortogonal
Se extrae la componente de un vector en la dirección de otro, obteniendo la “sombra” paralela a esa dirección. Sirve para descomponer vectores en componentes paralelas y perpendiculares a una dirección dada.

In [7]:
V=np.array([5,-3,2])
U=np.array([2,1,2])
proyeccion = np.dot(V, U) / np.dot(U, U) * U
print("Resultado de la proyección ortogonal: ")
print(proyeccion)

Resultado de la proyección ortogonal: 
[2.44444444 1.22222222 2.44444444]


##Ejercicio 8: Producto escalar de proyecciones
Se calculan las proyecciones de un mismo vector sobre dos direcciones distintas y luego se evalúa su producto escalar. Esto mide cuánto comparten en dirección esas proyecciones y si tienden a apuntar concordantemente o en direcciones opuestas.

In [8]:
V=np.array([3,-1,2])
U=np.array([2,2,-1])
W=np.array([1,4,-2])
proyeccion1 = np.dot(V, U) / np.dot(U, U) * U
proyeccion2 = np.dot(V, W) / np.dot(W, W) * W
producto_escalar = np.dot(proyeccion1, proyeccion2)
print("Resultado del producto escalar de proyecciones: ")
print(producto_escalar)

Resultado del producto escalar de proyecciones: 
-0.6349206349206349


##Ejercicio 9: Ortogonalizacion Gram-Schmidt
Se transforma un conjunto de vectores en una base ortogonal mediante el proceso de Gram–Schmidt. El resultado facilita cálculos (por ejemplo, proyecciones) y, si se normaliza, produce una base ortornormal muy útil en análisis numérico y geometría.

In [9]:
def gram_schmidt(vectores):
    ortogonales = []
    for v in vectores:
      for u in ortogonales:
        v = v-(np.dot(v,u)/np.dot(u,u))*u
      ortogonales.append(v)
    return ortogonales
v1=np.array([1,1,0], dtype=float)
v2=np.array([1,2,1], dtype=float)
v3=np.array([2,1,3], dtype=float)
resultado=gram_schmidt([v1,v2,v3])
print("Vectores ortogonales: ")
for v in resultado:
  print(v)

Vectores ortogonales: 
[1. 1. 0.]
[-0.5  0.5  1. ]
[ 1.33333333 -1.33333333  1.33333333]


##Ejercicio 10: Espacio nulo
Se determina la base del espacio nulo, es decir, todos los vectores que la matriz envía al vector cero. Conocer el espacio nulo permite describir soluciones homogéneas de sistemas lineales y entender la dependencia lineal entre columnas

In [10]:
A=Matrix([[1,2,0,3], [0,1,0,2], [0,0,1,1]])
nulo=A.nullspace()
print("Espacio nulo de la matriz: ")
print(nulo)

Espacio nulo de la matriz: 
[Matrix([
[ 1],
[-2],
[-1],
[ 1]])]
